project:
  execute-dir: project
  type: book

book:
  title: PREDICTING QUALITY OF HOME CARE LIQUID PRODUCTS
  date: "Ho Chi Minh City, March 28, 2024"
  author:
    name: "Nguyễn Đức Phú"
  abstract: "The industrial applications for machine learning are the main concern for the research community, with interpretability increasingly gaining attention. We contribute this study to propose an approach for a traditional problem in the industry of chemical engineering, predicting the quality of home care liquid products but only focusing on the explainability of the intelligence system. By conducting domain-based feature engineering, we ensure the inputs extracted from industrial instrument time series data are understandable by users. Two different approaches, which are using a transparent architecture like Linear Regression and conducting post hoc analysis with SHAP value for an ensemble model Random Forest Regression, are experimented with in the study. The results are promising in that the ensemble models achieved over 70% accuracy while the influencing features are aligned with domain expertise. In conclusion, the study provides a practical example of deploying an explainable artificial intelligence solution in a traditional industry such as chemical engineering."
  chapters:
    - index.qmd
    - Chapters/02_literature-review.qmd
    - Chapters/03_methodology.qmd
    - Chapters/04_result_analytics.qmd
    - Chapters/05_summary.qmd
    - Chapters/06_references.qmd
  appendices:
    - Appendices/AppendixA.qmd
  downloads: pdf
  repo-url: https://github.com/ducphuCS/master-thesis/
  repo-actions: [edit, source, issue]
  search: true

jupyter: python3
execute: 
  echo: false

thesis:
  supervisor: 
    name: Dr. Thoại Nam
  degree-name: Master of Science
  university: VIETNAM NATIONAL UNIVERSITY HO CHI MINH CITY
  department: HO CHI MINH UNIVERSITY OF TECHNOLOGY
  faculty: Faculty of Computer Science and Engineering
  declaration: "Frontmatter/declaration.tex"
  quotation:
    text: "It's not the destination, it's the journey."
    attribution: Ralph Waldo Emerson
  acknowledgements: "Frontmatter/acknowledgements.tex"
  # abbreviations: "Frontmatter/abbreviations.tex"
  # symbols: "Frontmatter/symbols.tex"
  # dedication: "Frontmatter/dedication.tex"
  logo: images/01_logobachkhoasang.png
  logo-height: "3cm"

bibliography: references.bib
cls: MastersDoctoralThesis.cls
csl: ieee.csl


format:
  html:
    theme: lux
  quarto-thesis-pdf:
    pdf-engine: lualatex

citeproc: true