# Conclusion

The magic of machine learning techniques and artificial intelligence in general has been proved in many aspects. In the industry of manufacturing, the applications of machine learning have been pushed forward in recent years to resolve both traditional and new-coming problems. The interpretability has also received more attention in the counteract for the raising of sophisticated model architecture. Stakeholders now care more about the reasoning behind each prediction rather than the overall accuracy of the deployed models.

The objective of the research is to expand the contribution of machine learning in the domain of manufacturing industries, the home care chemical to be specific, as well as to provide a use case in which explainable artificial intelligence plays a guiding role in all the steps of constructing an intelligence system. Linear Regression and Random Forest are the representatives of two types of models in the concept of XAI, which are transparent and black-box models. SHAP value plays the role of translators to explain the model results and the impact of features from the computer science computation to a human-understandable domain-based language.

In the study, we propose feature engineering methods for various time series, which can be categorized into many different groups. Each group of signals is applied with a customized and specialized algorithm, to provide a glance at an industrial processing system. The features then are the foundation to construct high-performance models that outperform their baseline. Another contribution is the application of SHAP, an indicator dedicated to explaining the usefulness of features in the process of output inference. The results are satisfactory since the top-of-the-table features are understandable and acceptable by the knowledge and experience from the considered domain.

However, during the research, we discover the potential playground for researchers to improve further. A feature-extracting process can be deployed to not only select the right features but also create breakthrough ones. Moreover, only two machine learning architectures take part in the experiment. Other transparent candidates such as kNN, Bayesian Network or Supporting Vector Machine have a bright future to achieve a better performance and, more importantly, provide a better explanation. Deep learning is an untouched facet and can be included in the next study.

A side effect found is the need to plan the industrial infrastructure that is stable in the manufacturing business and provides a foundation for machine learning applications. To be more detailed, the time series used in the study is not ensured in terms of accuracy and reliability. There are holes between the time series due to the downtime of the machine which are difficult to manage manually case-by-case.